services:
  - type: web
    name: App-m√©teo.daniel
    env: python 3.12.2
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn config.wsgi:application --workers 3 --bind 0.0.0.0:$PORT